version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_NAME=coinmena
      - DB_USER=coinmena
      - DB_PASS=coinmena
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"

  database:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

  redis:
    image: redis:6.2.6

  celery-worker:
    restart: always
    build:
      context: .
    volumes:
      - .:/app
    command: celery -A core worker -l info
    depends_on:
      - database
      - redis

  celery-beat:
    build: .
    command: celery -A core beat -l info
    volumes:
      - .:/app
    depends_on:
      - database
      - redis
      - celery-worker
volumes:
  postgres_data: