# Generated by Django 4.0.1 on 2022-01-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BtcUsd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency_code', models.CharField(max_length=5)),
                ('to_currency_code', models.CharField(max_length=5)),
                ('exchange_rate', models.FloatField()),
                ('date', models.DateTimeField()),
                ('time_zone', models.CharField(max_length=5)),
                ('bid_price', models.FloatField()),
                ('ask_price', models.FloatField()),
            ],
        ),
    ]
